export const productStyles = {
  card: {
    backgroundColor: "#ffffff",
    border: "1px solid #f0f0f0",
    borderRadius: "12px",
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    transition: "all 0.3s ease",
    boxShadow: "0 2px 8px rgba(0,0,0,0.08)",
    cursor: "pointer",
    ":hover": {
      transform: "translateY(-4px)",
      boxShadow: "0 8px 25px rgba(0,0,0,0.15)",
    },
  },
  image: {
    width: "100%",
    height: "180px",
    objectFit: "contain",
    marginBottom: "12px",
    borderRadius: "8px",
  },
  name: {
    fontSize: "16px",
    fontWeight: "600",
    color: "#1a1a1a",
    marginBottom: "8px",
    lineHeight: "1.4",
  },
  category: {
    fontSize: "12px",
    color: "#666",
    marginBottom: "12px",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    fontWeight: "500",
  },
  priceRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "auto",
  },
  price: {
    fontSize: "18px",
    fontWeight: "700",
    color: "#4CAF50",
  },
  offerPrice: {
    fontSize: "14px",
    color: "#999",
    textDecoration: "line-through",
    marginRight: "8px",
  },
  button: {
    padding: "8px 16px",
    fontSize: "14px",
    fontWeight: "600",
    border: "2px solid #4CAF50",
    backgroundColor: "#fff",
    color: "#4CAF50",
    borderRadius: "8px",
    cursor: "pointer",
    transition: "all 0.3s ease",
    ":hover": {
      backgroundColor: "#4CAF50",
      color: "#fff",
      transform: "scale(1.05)",
    },
  },
};
